language: rust
os:
    - linux
    - osx
env:
    global:
        - secure: TySUUmQTac573GGoah6pdfz5ZvfxWh9mLThTpubONEUHyeNR1DPZkQ1NfvslAkGKU3iSRYZ2HOKyaeDxh8s8GiyT+gty93z0cvBCeXZlgSqIUOJO77yurnr16dwluh4ySgBMhLU8EPJAc3MG02W3YjKsDcQr1NmeM3Mb4fQf6Ng=
        - LD_LIBRARY_PATH: /usr/local/lib
install:
    # SDL2
    - curl -O http://www.libsdl.org/release/SDL2-2.0.0.tar.gz
    - tar -xzvf SDL2-2.0.0.tar.gz
    - (cd SDL2-2.0.0 && ./configure && make && sudo make install)
before_script:
    - rustc -v
    - cargo -V
script:
    - cargo build -v
    - cargo test -v
    - cargo doc -v
    - cd examples/image_iter/
    - cargo build -v
    - cargo doc -v
after_success:
    - cp -R target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
    - rm -r doc
