[package]

name = "piston2d-gfx_graphics"
version = "0.0.2"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["graphics", "2d", "gfx"]
description = "A Gfx 2D back-end for the Piston game engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/gfx_graphics.git"
homepage = "https://github.com/PistonDevelopers/gfx_graphics"

[lib]

name = "gfx_graphics"
path = "src/lib.rs"

[dependencies.piston2d-graphics]
git = "https://github.com/pistondevelopers/graphics"
#version = "0.0.6"

[dependencies.piston-gfx_texture]
git = "https://github.com/pistondevelopers/gfx_texture"
#version = "0.0.0"

[dependencies.image]
git = "https://github.com/pistondevelopers/image"
#version = "~0.2.0"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs"
#version = "0.1.0"

[dependencies.gfx_macros]
git = "https://github.com/gfx-rs/gfx-rs"
#version = "0.1.0"

[dev-dependencies.shader_version]
git = "https://github.com/pistondevelopers/shader_version"
#version = "0.0.1"

[dev-dependencies.pistoncore-event]
git = "https://github.com/pistondevelopers/event"
#version = "0.0.5"

[dev-dependencies.pistoncore-sdl2_window]
git = "https://github.com/pistondevelopers/sdl2_window"
#version = "0.0.0"

[dev-dependencies.quack]
git = "https://github.com/pistondevelopers/quack"
#version = "0.0.2"

[dev-dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2"
#version = "0.0.18"

